site_name: Trickster
site_url: http://tricksterproxy.io/

repo_url: https://github.com/tricksterproxy/trickster
repo_name: tricksterproxy/trickster


theme:
  name: material
  logo: ../../images/logos/trickster-logo.svg

  palette:
    - scheme: trickster
      accent: green

extra_css:
  - stylesheets/extra.css

